# Use the official Node.js image as a base image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server application code
COPY . .

# Expose the port the app runs on
EXPOSE 3001

# Command to run the server application
CMD ["npm", "run", "start-server"]