version: '3.8'

services:
  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NODE_ENV=production

  server:
    build:
      context: ./src/server
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://db:27017/newsdb

  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
