import type { Metadata } from "next";
import "./globals.css";
import { StoreProvider } from '../app/lib/StoreProvider';
import { Navbar, Footer } from "./components";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col h-full">
        <StoreProvider>
          <Navbar />
          <main className="flex-grow overflow-auto">
            {children}
          </main>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}

